apiVersion: v1
kind: Namespace
metadata:
  name: drift-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api
  namespace: drift-demo
  labels:
    app: checkout-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-api
  template:
    metadata:
      labels:
        app: checkout-api
    spec:
      containers:
        - name: checkout-api
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-api
  namespace: drift-demo
spec:
  type: ClusterIP
  selector:
    app: checkout-api
  ports:
    - name: http
      port: 80
      targetPort: 80
